### ISSUE TITLE
commerce marketplace revenue share model rate contradiction

### ISSUE THREAD

**Issue by ronpadz** [AdobeDocs/commerce-marketplace#18]
https://developer.adobe.com/commerce/marketplace/guides/sellers/revenue-share/ states "85/15 revenue share split, with 85% of the revenue for the provider and 15% for Adobe

On this page there is a link to a .PDF https://docs.magento.com/m2/pdf/marketplace/Marketplace_Revenue_Share.pdf that states the revenue share as 70/30

### Expected Behaviour 
There should be a single version of the truth

### Actual Behaviour
There are two versions of the truth

### Reproduce Scenario (including but not limited to)
Click on included links

**Comment by jeff-matthews** [comment]
Updated PDF has been published.
