### ISSUE TITLE
Tag campos costumizados para API

### ISSUE THREAD

**Issue by janaharing** [AdobeDocs/commerce-marketplace#71]
Preciso localizar as tag's para os campos abaixo:

Altura;
Largura;
Profundidade;

Na API produtos. preciso dessa informação para preencher no meu ERP (Bling), que esta integrado ao Magento2

![Campos_costumizados_integração_Magento_ErpBling](https://user-images.githubusercontent.com/111304181/221966918-93fb80c4-eff9-4eee-8c85-053ecba575b4.JPG)

Preciso

**Comment by dobooth** [comment]
Hi @janaharing Thanks for filing. Can you please reference a documentation page that is incorrect? We are not sure where to find this issue.

**Comment by hguthrie** [comment]
Closing due to lack of response. If you still have this problem, you can reopen this issue and provide more details, such as a link to the article in question. Thanks!
